export type AuditCategory =
  | 'SOP'
  | 'App'
  | 'Approval'
  | 'Deployment'
  | 'Evaluation'
  | 'Helper'
  | 'Guardrail'
  | 'Knowledge'
  | 'Model'
  | 'Access';

export interface AuditEntry {
  id: string;
  timestamp: string;
  actorPersonaId: string;
  actorName: string;
  category: AuditCategory;
  action: string;
  target: string;
  summary: string;
  projectId?: string;
  appId?: string;
  payload?: Record<string, unknown>;
}

export const auditEntries: AuditEntry[] = [
  {
    id: 'aud_1',
    timestamp: '2026-05-28T11:24:18Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Evaluation',
    action: 'Continuous evaluation completed',
    target: 'app:card-dispute-triage',
    summary: 'Run #14 completed. Overall score 94 (↑ +2.4). Reg E disclosure +5, Intent coverage flat.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
    payload: { runId: 'run_14', delta: 2.4, baseline: 80 },
  },
  {
    id: 'aud_2',
    timestamp: '2026-05-28T11:14:03Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Guardrail',
    action: 'Guardrail triggered (blocked)',
    target: 'app:card-dispute-triage',
    summary: 'Guardrail "do-not-quote-final-rates" prevented response containing a hard rate quote.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
    payload: { guardrailId: 'gp_no_final_rates', conversationId: 'conv_44219' },
  },
  {
    id: 'aud_3',
    timestamp: '2026-05-28T10:52:41Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'Helper',
    action: 'Helper action confirmed',
    target: 'app:hardship-assist',
    summary: 'Confirmed: add guardrail "Require income-loss documentation before drafting payment plan".',
    appId: 'app_hardship_assist',
    projectId: 'proj_collections',
    payload: { helperConversationId: 'hc_882', action: 'add_guardrail' },
  },
  {
    id: 'aud_4',
    timestamp: '2026-05-28T10:18:12Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'App',
    action: 'App submitted for approval',
    target: 'app:hardship-assist',
    summary: 'Submitted hardship-assist v1 for compliance review. 2 reviewers notified.',
    appId: 'app_hardship_assist',
    projectId: 'proj_collections',
  },
  {
    id: 'aud_5',
    timestamp: '2026-05-28T09:42:00Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'SOP',
    action: 'SOP uploaded',
    target: 'sop:Hardship_Plans_2026.docx',
    summary: 'Hardship Plans SOP v1 uploaded. Auto-generation produced hardship-assist app.',
    projectId: 'proj_collections',
  },
  {
    id: 'aud_6',
    timestamp: '2026-05-28T08:00:00Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Evaluation',
    action: 'Scheduled evaluation completed',
    target: 'app:account-opening-assistant',
    summary: 'Run #9 completed. Overall score 91 (↑ +1.2). Citation coverage trending down (96% → 92%).',
    appId: 'app_account_opening',
    projectId: 'proj_member_onboarding',
  },
  {
    id: 'aud_7',
    timestamp: '2026-05-27T22:31:08Z',
    actorPersonaId: 'u_rs',
    actorName: 'Rina Salgado',
    category: 'Approval',
    action: 'Co-approved submission',
    target: 'app:fraud-triage v1',
    summary: 'Co-approved fraud-triage. Awaiting Marco Davis to complete dual approval.',
    appId: 'app_fraud_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_8',
    timestamp: '2026-05-27T18:22:54Z',
    actorPersonaId: 'u_jc',
    actorName: 'Jordan Chen',
    category: 'Knowledge',
    action: 'Knowledge source added',
    target: 'kb:Cornerstone Card Services FAQ',
    summary: 'Added Confluence source "Cornerstone Card Services FAQ" with project scope = Card Services.',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_9',
    timestamp: '2026-05-27T16:01:32Z',
    actorPersonaId: 'u_jc',
    actorName: 'Jordan Chen',
    category: 'Model',
    action: 'Model endpoint configured',
    target: 'model:cornerstone-azure-gpt4o',
    summary: 'Configured Azure OpenAI GPT-4o (cornerstone Azure tenant) as response-generation override.',
  },
  {
    id: 'aud_10',
    timestamp: '2026-05-27T14:48:19Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'Access',
    action: 'Signed in via SSO',
    target: 'tenant:cu_cornerstone',
    summary: 'SAML SSO sign-in from 192.0.2.14 · Chrome / macOS.',
  },
  {
    id: 'aud_11',
    timestamp: '2026-05-27T11:10:07Z',
    actorPersonaId: 'u_rs',
    actorName: 'Rina Salgado',
    category: 'Approval',
    action: 'Requested changes',
    target: 'app:loan-application-intake v1',
    summary: 'Requested changes: "Rate-language compliance category at 75. Add a guardrail before resubmission."',
    appId: 'app_loan_intake',
    projectId: 'proj_lending',
  },
  {
    id: 'aud_12',
    timestamp: '2026-05-27T10:55:14Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'App',
    action: 'App submitted for approval',
    target: 'app:loan-application-intake',
    summary: 'Submitted loan-application-intake v1. Below pilot baseline of 80 (score 79).',
    appId: 'app_loan_intake',
    projectId: 'proj_lending',
  },
  {
    id: 'aud_13',
    timestamp: '2026-05-27T09:22:00Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Guardrail',
    action: 'Baseline guardrail version bumped',
    target: 'tenant:cu_cornerstone',
    summary: 'TCPA-safe outbound guardrail updated to v2 by Platform Team. Active on all apps.',
  },
  {
    id: 'aud_14',
    timestamp: '2026-05-26T20:14:48Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'Helper',
    action: 'Helper action skipped',
    target: 'app:hardship-assist',
    summary: 'Skipped: Helper proposal to reword payment-plan offer template.',
    appId: 'app_hardship_assist',
    projectId: 'proj_collections',
  },
  {
    id: 'aud_15',
    timestamp: '2026-05-26T16:38:21Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Deployment',
    action: 'Configuration snapshot recorded',
    target: 'app:fraud-triage',
    summary: 'Approval signatures captured. Ready for deployment.',
    appId: 'app_fraud_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_16',
    timestamp: '2026-05-26T14:12:05Z',
    actorPersonaId: 'u_rs',
    actorName: 'Rina Salgado',
    category: 'Approval',
    action: 'Approved submission',
    target: 'app:account-opening-assistant v2',
    summary: 'Approved account-opening-assistant v2 for deployment.',
    appId: 'app_account_opening',
    projectId: 'proj_member_onboarding',
  },
  {
    id: 'aud_17',
    timestamp: '2026-05-26T13:54:33Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Evaluation',
    action: 'Continuous evaluation triggered alert',
    target: 'app:hardship-assist',
    summary: 'Hardship eligibility logic dropped from 82 to 78 between run #10 and run #11.',
    appId: 'app_hardship_assist',
    projectId: 'proj_collections',
  },
  {
    id: 'aud_18',
    timestamp: '2026-05-26T11:30:00Z',
    actorPersonaId: 'u_jc',
    actorName: 'Jordan Chen',
    category: 'Knowledge',
    action: 'Knowledge source marked stale',
    target: 'kb:Hardship programs',
    summary: 'Confluence source last updated > 30 days ago. CU Admin notified.',
    projectId: 'proj_collections',
  },
  {
    id: 'aud_19',
    timestamp: '2026-05-26T10:11:42Z',
    actorPersonaId: 'u_md',
    actorName: 'Marco Davis',
    category: 'Approval',
    action: 'Approved submission',
    target: 'app:card-dispute-triage v3',
    summary: 'Co-approved card-dispute-triage v3 (with Rina). Dual approval complete.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_20',
    timestamp: '2026-05-26T10:00:18Z',
    actorPersonaId: 'u_rs',
    actorName: 'Rina Salgado',
    category: 'Approval',
    action: 'Approved submission',
    target: 'app:card-dispute-triage v3',
    summary: 'Approved card-dispute-triage v3.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_21',
    timestamp: '2026-05-25T22:42:00Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Deployment',
    action: 'App deployed',
    target: 'app:card-dispute-triage v3',
    summary: 'Deployed to all members across digital + voice channels. Mission Control surfaces activated.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_22',
    timestamp: '2026-05-25T22:38:51Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'Deployment',
    action: 'Deployment initiated',
    target: 'app:card-dispute-triage v3',
    summary: 'Process Owner initiated deployment of card-dispute-triage v3.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_23',
    timestamp: '2026-05-25T15:11:09Z',
    actorPersonaId: 'u_np',
    actorName: 'Demo User',
    category: 'Helper',
    action: 'Helper action confirmed',
    target: 'app:card-dispute-triage',
    summary: 'Confirmed: re-attach Reg E playbook to Compliance sub-agent.',
    appId: 'app_card_dispute_triage',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_24',
    timestamp: '2026-05-25T11:02:30Z',
    actorPersonaId: 'u_jc',
    actorName: 'Jordan Chen',
    category: 'Access',
    action: 'Project member added',
    target: 'project:Card Services',
    summary: 'Added Marco Davis to Card Services project with role Compliance Co-Reviewer.',
    projectId: 'proj_card_services',
  },
  {
    id: 'aud_25',
    timestamp: '2026-05-24T19:00:00Z',
    actorPersonaId: 'system',
    actorName: 'system',
    category: 'Knowledge',
    action: 'Take-down propagated',
    target: 'kb:Old hardship FAQ',
    summary: 'Deprecated source removed from retrieval caches within 8 minutes. Dependent apps notified.',
    projectId: 'proj_collections',
  },
];

export function getAuditEntryById(id: string): AuditEntry | undefined {
  return auditEntries.find((e) => e.id === id);
}
